//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_V2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Test_v2Entities : DbContext
    {
        public Test_v2Entities()
            : base("name=Test_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_Staff> Tbl_Staff { get; set; }
        public virtual DbSet<Tbl_Store> Tbl_Store { get; set; }
    
        public virtual ObjectResult<sp_GetProducts_Result> sp_GetProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProducts_Result>("sp_GetProducts");
        }
    
        public virtual ObjectResult<sp_GetStaff_Result> sp_GetStaff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStaff_Result>("sp_GetStaff");
        }
    
        public virtual ObjectResult<sp_GetStore_Result> sp_GetStore()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStore_Result>("sp_GetStore");
        }
    }
}
