//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        public int productid { get; set; }
        public Nullable<int> storeid { get; set; }
        public Nullable<int> staffid { get; set; }
        public string productname { get; set; }
        public Nullable<int> productquantity { get; set; }
        public Nullable<decimal> productprice { get; set; }
    
        public virtual Tbl_Staff Tbl_Staff { get; set; }
        public virtual Tbl_Store Tbl_Store { get; set; }
    }
}
