//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Staff()
        {
            this.Tbl_Product = new HashSet<Tbl_Product>();
        }
    
        public int staffid { get; set; }
        public Nullable<int> storeid { get; set; }
        public string staffname { get; set; }
        public string staffaddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }
        public virtual Tbl_Store Tbl_Store { get; set; }
    }
}
