//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API_Token
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SECURITY_DBEntities : DbContext
    {
        public SECURITY_DBEntities()
            : base("name=SECURITY_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
    
        public virtual ObjectResult<sp_Validate_User_Result> sp_Validate_User(string userName, string userPassword)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Validate_User_Result>("sp_Validate_User", userNameParameter, userPasswordParameter);
        }
    
        public virtual ObjectResult<sp_Validate_Client_Result> sp_Validate_Client(string clientId, string clientSecret)
        {
            var clientIdParameter = clientId != null ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(string));
    
            var clientSecretParameter = clientSecret != null ?
                new ObjectParameter("ClientSecret", clientSecret) :
                new ObjectParameter("ClientSecret", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Validate_Client_Result>("sp_Validate_Client", clientIdParameter, clientSecretParameter);
        }
    }
}
